services:
  proxy:
    build:
      context: nginx
      dockerfile: ./Dockerfile.prod
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - network-desafio
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --init-file /var/lib/inicializador/init.sql
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/var/lib/inicializador/init.sql
    networks:
      - network-desafio


  app:
    build:
      context: nodejs
      dockerfile: ./Dockerfile.prod
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - network-desafio
    depends_on:
      - db



networks:
  network-desafio:
    driver: bridge
    
